image: alpine:latest

pages:
  stage: deploy
  script:
    - apk add --no-cache bash
    - mkdir -p public
    - cp -r ./ubo-resume.html ./public/index.html
    - cp -r ./css ./images ./README.md ./public/ || true
  artifacts:
    paths:
      - public
  only:
    - main
